version: '3'

services:
  nodeapp:
    image: fodin/rs-node-app:1.0
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    restart:
      always #on-failure
    depends_on:
      - postgres
    networks:
      - mynet
    environment:
      PORT: ${PORT}

  postgres:
    image: fodin/postgres:13.3-fixed
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynet
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  mynet:
    driver: bridge
